# Homework 2.4

*Homework is designed to both test your knowlege and challenge you to apply familiar concepts to new applications. Answer clearly and completely. You are welcomed and encouraged to work in groups so long as your work is your own. Submit your figures and answers to [Gradescope](https://www.gradescope.com).*

In [ ]:
# Imports
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

# File Path
file_path = 'https://tayweid.github.io/econ-0150/parts/part-2-4/data/'

## Q1. Grouping Amazon Book Sales

We'll explore the list of 50 bestselling Amazon books each year between 2009 and 2021. The column `Genre` describes whether the bestseller is Fiction or Non-Fiction.

In [ ]:
books = pd.read_csv(file_path + 'amazon_book_sales.csv', index_col=0)
books.head()

,Name,Author,User Rating,Reviews,Price,Year,Genre,Median_Price
0,"Act Like a Lady, Think Like a Man: What Men Re...",Steve Harvey,4.6,5013,17,2009,Non Fiction,12.0
1,Arguing with Idiots: How to Stop Small Minds a...,Glenn Beck,4.6,798,5,2009,Non Fiction,12.0
2,"Breaking Dawn (The Twilight Saga, Book 4)",Stephenie Meyer,4.6,9769,13,2009,Fiction,12.0
3,Crazy Love: Overwhelmed by a Relentless God,Francis Chan,4.7,1542,14,2009,Non Fiction,12.0
4,Dead And Gone: A Sookie Stackhouse Novel (Sook...,Charlaine Harris,4.6,1541,4,2009,Fiction,12.0

a) Create a figure that will display the count of fiction books for each year.

b) In the year with the most fiction bestsellers, how many bestsellers are fiction books?

## Q2. Marriage Rates by Continent

The following questions are based on **crude marriage rates** — numbers of marriages per one thousand inhabitants — in 1990 and 2019. Each row represents a different country.

In [ ]:
marriage = pd.read_csv(file_path + 'marriage_rates_by_continent.csv')
marriage.head()

      Country  Marriage_Rate_per_1000      Continent
0   Palestine                    10.0           Asia
1        Fiji                     9.8        Oceania
2       Egypt                     9.6         Africa
3     Bahamas                     9.5  North America
4  Uzbekistan                     9.5           Asia

a) Create a figure showing the mean marriage rate by continent.

b) Which continent has the lowest mean marraige rate?